openapi: 3.0.0
info:
  title: EMAIL-MARKETING-SEQ
  contact: {}
  version: 1.0.0
servers:
  - url: https://email-marketing-seq.onrender.com/api/v1
    variables: {}

paths:
  /auth/register:
    post:
      tags:
        - USERS
      summary: REGISTER
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: chandu
                email: chandanchuphal124
                password: "123456"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

      security: []

  /auth/login:
    post:
      tags:
        - USERS
      summary: LOGIN
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: logan
                password: "123456"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

      security: []

  /auth/logout:
    post:
      tags:
        - USERS
      summary: LOGOUT
      requestBody:
        content: {}
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

      security: []

  /coldemail:
    post:
      tags:
        - EMAIL
      summary: COLDEMAIL
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                to: cchuphal4@gmail.com
                subject: For jobs
                text: Give me job.. please
                delay: 5 seconds
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

      security:
        - CookieAuth: []

  /coldemail/get:
    get:
      tags:
        - EMAIL
      summary: GET COLDEMAILS
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

      security:
        - CookieAuth: []

components:
  schemas:
    REGISTERREQUEST:
      title: REGISTERREQUEST
      required:
        - username
        - email
        - password
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      examples:
        - username: King
          email: king@gmail.com
          password: "123456"
    LOGINREQUEST:
      title: LOGINREQUEST
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      examples:
        - username: Paul
          password: "123456"
    LOGOUTREQUEST:
      title: LOGOUTREQUEST
      required:
        - name
      type: object
      properties:
        name:
          type: string
      examples:
        - name: logan

    COLDEMAILREQUEST:
      title: COLDEMAILREQUEST
      required:
        - to
        - subject
        - text
        - delay

      type: object
      properties:
        to:
          type: string
        subject:
          type: string
        text:
          type: string
        delay:
          type: string

      examples:
        - to: cchuphal4@gmail.com
          subject: For jobs
          text: Give me job.. please
          delay: 5 seconds

  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: jwt
      description: Cookie-based authentication
security:
  - CookieAuth: []
tags:
  - name: USERS
  - name: EMAIL
